---

language: python

python:
  - '3.6'

script:
  # - sudo docker-compose up -d
  - sudo apt-get update && sudo apt-get install python-pip python3-pip
  - sudo pip install pipenv
  - sudo pipenv install
  - sudo pipenv run pytest