---

services:
  - docker

language: python

python:
  - '3.6'

install:
  - sudo apt-get update && sudo apt-get install python3-pip
  - sudo pip install pipenv
  - sudo pipenv install

script:
  - sudo pipenv run pytest tests/test_conn.py
  - sudo docker build -t hello_world:latest .
  - sudo docker run -p 5000:5000 -d hello_world:latest
  - sudo pipenv run pytest tests/test_docker.py
  - sudo docker push thomasbar/hello_world:latest